/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package darielsevilla_examen1p2;

/**
 *
 * @author HP
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wd_crudMenu = new javax.swing.JFrame();
        pn_crudPrincipal = new javax.swing.JPanel();
        tp_opcionesCrud = new javax.swing.JTabbedPane();
        pn_crearPc = new javax.swing.JPanel();
        pn_crearLaptop = new javax.swing.JPanel();
        pn_listar = new javax.swing.JPanel();
        pn_Eliminar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bt_ingreseEscritorio = new javax.swing.JButton();
        bt_ingreseLaptop = new javax.swing.JButton();
        bt_listar = new javax.swing.JButton();
        bt_regreso = new javax.swing.JButton();
        pn_menu = new javax.swing.JPanel();
        lb_tituloMenu = new javax.swing.JLabel();
        bt_crudPC = new javax.swing.JButton();
        bt_crudPC1 = new javax.swing.JButton();
        bt_IngresePC = new javax.swing.JButton();
        bt_salida = new javax.swing.JButton();

        wd_crudMenu.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_crudPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        pn_crudPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tp_opcionesCrud.setBackground(new java.awt.Color(153, 153, 153));
        tp_opcionesCrud.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pn_crearPcLayout = new javax.swing.GroupLayout(pn_crearPc);
        pn_crearPc.setLayout(pn_crearPcLayout);
        pn_crearPcLayout.setHorizontalGroup(
            pn_crearPcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        pn_crearPcLayout.setVerticalGroup(
            pn_crearPcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        tp_opcionesCrud.addTab("tab1", pn_crearPc);

        javax.swing.GroupLayout pn_crearLaptopLayout = new javax.swing.GroupLayout(pn_crearLaptop);
        pn_crearLaptop.setLayout(pn_crearLaptopLayout);
        pn_crearLaptopLayout.setHorizontalGroup(
            pn_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        pn_crearLaptopLayout.setVerticalGroup(
            pn_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        tp_opcionesCrud.addTab("tab2", pn_crearLaptop);

        javax.swing.GroupLayout pn_listarLayout = new javax.swing.GroupLayout(pn_listar);
        pn_listar.setLayout(pn_listarLayout);
        pn_listarLayout.setHorizontalGroup(
            pn_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        pn_listarLayout.setVerticalGroup(
            pn_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        tp_opcionesCrud.addTab("tab3", pn_listar);

        javax.swing.GroupLayout pn_EliminarLayout = new javax.swing.GroupLayout(pn_Eliminar);
        pn_Eliminar.setLayout(pn_EliminarLayout);
        pn_EliminarLayout.setHorizontalGroup(
            pn_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        pn_EliminarLayout.setVerticalGroup(
            pn_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        tp_opcionesCrud.addTab("tab4", pn_Eliminar);

        pn_crudPrincipal.add(tp_opcionesCrud, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -30, 490, 470));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_ingreseEscritorio.setText("Ingrese PC escritorio");
        jPanel2.add(bt_ingreseEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 45, -1, -1));

        bt_ingreseLaptop.setText("Ingrese Laptop");
        bt_ingreseLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ingreseLaptopActionPerformed(evt);
            }
        });
        jPanel2.add(bt_ingreseLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 132, -1, -1));

        bt_listar.setText("Listar");
        jPanel2.add(bt_listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 212, -1, -1));

        bt_regreso.setText("Salida");
        jPanel2.add(bt_regreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 279, -1, -1));

        pn_crudPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 161, 432));

        wd_crudMenu.getContentPane().add(pn_crudPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_menu.setBackground(new java.awt.Color(204, 204, 204));

        lb_tituloMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_tituloMenu.setForeground(new java.awt.Color(0, 0, 0));
        lb_tituloMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tituloMenu.setText("Menu principal");

        bt_crudPC.setBackground(new java.awt.Color(153, 153, 153));
        bt_crudPC.setForeground(new java.awt.Color(0, 0, 0));
        bt_crudPC.setText("Ingrese PC");

        bt_crudPC1.setBackground(new java.awt.Color(153, 153, 153));
        bt_crudPC1.setForeground(new java.awt.Color(0, 0, 0));
        bt_crudPC1.setText("Crud pc");

        bt_IngresePC.setBackground(new java.awt.Color(153, 153, 153));
        bt_IngresePC.setForeground(new java.awt.Color(0, 0, 0));
        bt_IngresePC.setText("Crud pc");

        bt_salida.setBackground(new java.awt.Color(153, 153, 153));
        bt_salida.setForeground(new java.awt.Color(0, 0, 0));
        bt_salida.setText("Crud pc");
        bt_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_menuLayout = new javax.swing.GroupLayout(pn_menu);
        pn_menu.setLayout(pn_menuLayout);
        pn_menuLayout.setHorizontalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(lb_tituloMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_menuLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_crudPC, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
            .addGroup(pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_menuLayout.createSequentialGroup()
                    .addContainerGap(134, Short.MAX_VALUE)
                    .addComponent(bt_crudPC1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(112, 112, 112)))
            .addGroup(pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_menuLayout.createSequentialGroup()
                    .addContainerGap(134, Short.MAX_VALUE)
                    .addComponent(bt_IngresePC, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(112, 112, 112)))
        );
        pn_menuLayout.setVerticalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lb_tituloMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(bt_crudPC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_menuLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(bt_crudPC1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(273, Short.MAX_VALUE)))
            .addGroup(pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_menuLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(bt_IngresePC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(273, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salidaActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_salidaActionPerformed

    private void bt_ingreseLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ingreseLaptopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ingreseLaptopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_IngresePC;
    private javax.swing.JButton bt_crudPC;
    private javax.swing.JButton bt_crudPC1;
    private javax.swing.JButton bt_ingreseEscritorio;
    private javax.swing.JButton bt_ingreseLaptop;
    private javax.swing.JButton bt_listar;
    private javax.swing.JButton bt_regreso;
    private javax.swing.JButton bt_salida;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_tituloMenu;
    private javax.swing.JPanel pn_Eliminar;
    private javax.swing.JPanel pn_crearLaptop;
    private javax.swing.JPanel pn_crearPc;
    private javax.swing.JPanel pn_crudPrincipal;
    private javax.swing.JPanel pn_listar;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JTabbedPane tp_opcionesCrud;
    private javax.swing.JFrame wd_crudMenu;
    // End of variables declaration//GEN-END:variables
}
