/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package darielsevilla_examen1p2;

import java.util.ArrayList;
import java.util.InputMismatchException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class MainMenu extends javax.swing.JFrame {

    ArrayList<PC> pcs = new ArrayList();
    

    public MainMenu() {
        initComponents();
        wd_crudMenu.setSize(this.getSize());
        wd_crudMenu.setBounds(0, 0, 668, 480);
        wd_crudMenu.setVisible(false);
        wd_crudMenu.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wd_crudMenu = new javax.swing.JFrame();
        pn_crudPrincipal = new javax.swing.JPanel();
        tp_opcionesCrud = new javax.swing.JTabbedPane();
        pn_Eliminar = new javax.swing.JPanel();
        bt_elimnar = new javax.swing.JButton();
        cb_eliminar = new javax.swing.JComboBox<>();
        pn_crearLaptop = new javax.swing.JPanel();
        at1 = new javax.swing.JLabel();
        at2 = new javax.swing.JLabel();
        at3 = new javax.swing.JLabel();
        at4 = new javax.swing.JLabel();
        at5 = new javax.swing.JLabel();
        at6 = new javax.swing.JLabel();
        rb_rgbSi = new javax.swing.JRadioButton();
        rb_rgbNo = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        tf_ip = new javax.swing.JTextField();
        tf_mask = new javax.swing.JTextField();
        tf_marca = new javax.swing.JTextField();
        tf_def = new javax.swing.JTextField();
        tf_host = new javax.swing.JTextField();
        pn_listar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_listar = new javax.swing.JTextArea();
        pn_Crear = new javax.swing.JPanel();
        lb_escritorioAtributo1 = new javax.swing.JLabel();
        lb_escritorioAtributo2 = new javax.swing.JLabel();
        lb_escritorioAtributo3 = new javax.swing.JLabel();
        lb_escritorioAtributo4 = new javax.swing.JLabel();
        lb_escritorioAtributo5 = new javax.swing.JLabel();
        lb_escritorioAtributo6 = new javax.swing.JLabel();
        lb_escritorioAtributo7 = new javax.swing.JLabel();
        atriHost = new javax.swing.JTextField();
        atriMask = new javax.swing.JTextField();
        atriAlm = new javax.swing.JTextField();
        atriRam = new javax.swing.JTextField();
        atriIP = new javax.swing.JTextField();
        boxTipo = new javax.swing.JComboBox<>();
        boxGraphics = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        base = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bt_ingreseEscritorio = new javax.swing.JButton();
        bt_ingreseLaptop = new javax.swing.JButton();
        bt_listar = new javax.swing.JButton();
        bt_regreso = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bg_grupo1 = new javax.swing.ButtonGroup();
        pn_menu = new javax.swing.JPanel();
        lb_tituloMenu = new javax.swing.JLabel();
        bt_crudPC = new javax.swing.JButton();
        bt_crudPC1 = new javax.swing.JButton();
        bt_salida = new javax.swing.JButton();

        wd_crudMenu.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_crudPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        pn_crudPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tp_opcionesCrud.setBackground(new java.awt.Color(153, 153, 153));
        tp_opcionesCrud.setForeground(new java.awt.Color(0, 0, 0));

        pn_Eliminar.setBackground(new java.awt.Color(153, 153, 153));

        bt_elimnar.setBackground(new java.awt.Color(255, 0, 0));
        bt_elimnar.setForeground(new java.awt.Color(0, 0, 0));
        bt_elimnar.setText("eliminar");
        bt_elimnar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_elimnarActionPerformed(evt);
            }
        });

        cb_eliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pn_EliminarLayout = new javax.swing.GroupLayout(pn_Eliminar);
        pn_Eliminar.setLayout(pn_EliminarLayout);
        pn_EliminarLayout.setHorizontalGroup(
            pn_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_EliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_elimnar)
                .addGap(186, 186, 186))
            .addGroup(pn_EliminarLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(cb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pn_EliminarLayout.setVerticalGroup(
            pn_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_EliminarLayout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(cb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(bt_elimnar)
                .addGap(105, 105, 105))
        );

        tp_opcionesCrud.addTab("tab1", pn_Eliminar);

        pn_crearLaptop.setBackground(new java.awt.Color(153, 153, 153));

        at1.setForeground(new java.awt.Color(0, 0, 0));
        at1.setText("Host:");

        at2.setForeground(new java.awt.Color(0, 0, 0));
        at2.setText("IP:");

        at3.setForeground(new java.awt.Color(0, 0, 0));
        at3.setText("Mascara:");

        at4.setForeground(new java.awt.Color(0, 0, 0));
        at4.setText("Marca:");

        at5.setForeground(new java.awt.Color(0, 0, 0));
        at5.setText("Definición de pantalla:");

        at6.setForeground(new java.awt.Color(0, 0, 0));
        at6.setText("RGB:");

        bg_grupo1.add(rb_rgbSi);
        rb_rgbSi.setForeground(new java.awt.Color(0, 0, 0));
        rb_rgbSi.setSelected(true);
        rb_rgbSi.setText("Si");

        bg_grupo1.add(rb_rgbNo);
        rb_rgbNo.setForeground(new java.awt.Color(0, 0, 0));
        rb_rgbNo.setText("No");

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tf_ip.setBackground(new java.awt.Color(255, 255, 255));
        tf_ip.setForeground(new java.awt.Color(0, 0, 0));

        tf_mask.setBackground(new java.awt.Color(255, 255, 255));
        tf_mask.setForeground(new java.awt.Color(0, 0, 0));

        tf_marca.setBackground(new java.awt.Color(255, 255, 255));
        tf_marca.setForeground(new java.awt.Color(0, 0, 0));

        tf_def.setBackground(new java.awt.Color(255, 255, 255));
        tf_def.setForeground(new java.awt.Color(0, 0, 0));

        tf_host.setBackground(new java.awt.Color(255, 255, 255));
        tf_host.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pn_crearLaptopLayout = new javax.swing.GroupLayout(pn_crearLaptop);
        pn_crearLaptop.setLayout(pn_crearLaptopLayout);
        pn_crearLaptopLayout.setHorizontalGroup(
            pn_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_crearLaptopLayout.createSequentialGroup()
                .addGroup(pn_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_crearLaptopLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(pn_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_crearLaptopLayout.createSequentialGroup()
                                .addComponent(at3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pn_crearLaptopLayout.createSequentialGroup()
                                .addGroup(pn_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pn_crearLaptopLayout.createSequentialGroup()
                                        .addComponent(at6)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_rgbSi)
                                        .addGap(26, 26, 26)
                                        .addComponent(rb_rgbNo))
                                    .addGroup(pn_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(pn_crearLaptopLayout.createSequentialGroup()
                                            .addComponent(at1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tf_host, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pn_crearLaptopLayout.createSequentialGroup()
                                            .addComponent(at2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tf_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_crearLaptopLayout.createSequentialGroup()
                                            .addGroup(pn_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(at5)
                                                .addComponent(at4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(pn_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tf_def, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tf_mask, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))))
                    .addGroup(pn_crearLaptopLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(14, 14, 14))
        );
        pn_crearLaptopLayout.setVerticalGroup(
            pn_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_crearLaptopLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pn_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(at1)
                    .addComponent(tf_host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(at2)
                    .addComponent(tf_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pn_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(at3)
                    .addComponent(tf_mask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(pn_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(at4)
                    .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pn_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(at5)
                    .addComponent(tf_def, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(pn_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(at6)
                    .addComponent(rb_rgbSi)
                    .addComponent(rb_rgbNo))
                .addGap(112, 112, 112)
                .addComponent(jButton2)
                .addGap(15, 15, 15))
        );

        tp_opcionesCrud.addTab("tab2", pn_crearLaptop);

        pn_listar.setBackground(new java.awt.Color(153, 153, 153));

        ta_listar.setBackground(new java.awt.Color(255, 255, 255));
        ta_listar.setColumns(20);
        ta_listar.setForeground(new java.awt.Color(0, 0, 0));
        ta_listar.setRows(5);
        ta_listar.setEnabled(false);
        jScrollPane1.setViewportView(ta_listar);

        javax.swing.GroupLayout pn_listarLayout = new javax.swing.GroupLayout(pn_listar);
        pn_listar.setLayout(pn_listarLayout);
        pn_listarLayout.setHorizontalGroup(
            pn_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_listarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_listarLayout.setVerticalGroup(
            pn_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_listarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tp_opcionesCrud.addTab("tab3", pn_listar);

        pn_Crear.setBackground(new java.awt.Color(153, 153, 153));
        pn_Crear.setForeground(new java.awt.Color(0, 0, 0));

        lb_escritorioAtributo1.setForeground(new java.awt.Color(0, 0, 0));
        lb_escritorioAtributo1.setText("Host:");

        lb_escritorioAtributo2.setForeground(new java.awt.Color(0, 0, 0));
        lb_escritorioAtributo2.setText("IP:");

        lb_escritorioAtributo3.setForeground(new java.awt.Color(0, 0, 0));
        lb_escritorioAtributo3.setText("Ram:");

        lb_escritorioAtributo4.setForeground(new java.awt.Color(0, 0, 0));
        lb_escritorioAtributo4.setText("Mascara(ultimos digitos):");

        lb_escritorioAtributo5.setForeground(new java.awt.Color(0, 0, 0));
        lb_escritorioAtributo5.setText("Tipo:");

        lb_escritorioAtributo6.setForeground(new java.awt.Color(0, 0, 0));
        lb_escritorioAtributo6.setText("Almacenamiento:");

        lb_escritorioAtributo7.setForeground(new java.awt.Color(0, 0, 0));
        lb_escritorioAtributo7.setText("Tarjeta gráfica:");

        atriHost.setBackground(new java.awt.Color(255, 255, 255));
        atriHost.setForeground(new java.awt.Color(0, 0, 0));
        atriHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atriHostActionPerformed(evt);
            }
        });

        atriMask.setBackground(new java.awt.Color(255, 255, 255));
        atriMask.setForeground(new java.awt.Color(0, 0, 0));

        atriAlm.setBackground(new java.awt.Color(255, 255, 255));
        atriAlm.setForeground(new java.awt.Color(0, 0, 0));

        atriRam.setBackground(new java.awt.Color(255, 255, 255));
        atriRam.setForeground(new java.awt.Color(0, 0, 0));

        atriIP.setBackground(new java.awt.Color(255, 255, 255));
        atriIP.setForeground(new java.awt.Color(0, 0, 0));

        boxTipo.setBackground(new java.awt.Color(255, 255, 255));
        boxTipo.setForeground(new java.awt.Color(0, 0, 0));
        boxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HDD", "SSD" }));

        boxGraphics.setBackground(new java.awt.Color(255, 255, 255));
        boxGraphics.setForeground(new java.awt.Color(0, 0, 0));
        boxGraphics.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No", " " }));
        boxGraphics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxGraphicsActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_CrearLayout = new javax.swing.GroupLayout(pn_Crear);
        pn_Crear.setLayout(pn_CrearLayout);
        pn_CrearLayout.setHorizontalGroup(
            pn_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_CrearLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pn_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pn_CrearLayout.createSequentialGroup()
                        .addComponent(lb_escritorioAtributo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atriHost, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_CrearLayout.createSequentialGroup()
                        .addComponent(lb_escritorioAtributo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(atriIP, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_CrearLayout.createSequentialGroup()
                        .addGroup(pn_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_escritorioAtributo3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_escritorioAtributo4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_escritorioAtributo5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_escritorioAtributo7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_escritorioAtributo6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pn_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(atriAlm, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atriRam, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atriMask, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxGraphics, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_CrearLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        pn_CrearLayout.setVerticalGroup(
            pn_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_CrearLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(pn_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_escritorioAtributo1)
                    .addComponent(atriHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_escritorioAtributo2)
                    .addComponent(atriIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_escritorioAtributo4)
                    .addComponent(atriMask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(pn_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_escritorioAtributo3)
                    .addComponent(atriRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pn_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_escritorioAtributo6)
                    .addComponent(atriAlm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pn_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_escritorioAtributo5)
                    .addComponent(boxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pn_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_escritorioAtributo7)
                    .addComponent(boxGraphics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );

        tp_opcionesCrud.addTab("tab4", pn_Crear);

        base.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        tp_opcionesCrud.addTab("tab5", base);

        pn_crudPrincipal.add(tp_opcionesCrud, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -30, 490, 470));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_ingreseEscritorio.setText("Ingrese PC escritorio");
        bt_ingreseEscritorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ingreseEscritorioActionPerformed(evt);
            }
        });
        jPanel2.add(bt_ingreseEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 45, -1, -1));

        bt_ingreseLaptop.setText("Ingrese Laptop");
        bt_ingreseLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ingreseLaptopActionPerformed(evt);
            }
        });
        jPanel2.add(bt_ingreseLaptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 132, -1, -1));

        bt_listar.setText("Listar");
        bt_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_listarActionPerformed(evt);
            }
        });
        jPanel2.add(bt_listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 212, -1, -1));

        bt_regreso.setText("Salida");
        bt_regreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_regresoActionPerformed(evt);
            }
        });
        jPanel2.add(bt_regreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(bt_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 279, -1, -1));

        pn_crudPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 161, 440));

        wd_crudMenu.getContentPane().add(pn_crudPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_menu.setBackground(new java.awt.Color(204, 204, 204));

        lb_tituloMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_tituloMenu.setForeground(new java.awt.Color(0, 0, 0));
        lb_tituloMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tituloMenu.setText("Menu principal");

        bt_crudPC.setBackground(new java.awt.Color(153, 153, 153));
        bt_crudPC.setForeground(new java.awt.Color(0, 0, 0));
        bt_crudPC.setText("Ingrese PC");
        bt_crudPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crudPCActionPerformed(evt);
            }
        });

        bt_crudPC1.setBackground(new java.awt.Color(153, 153, 153));
        bt_crudPC1.setForeground(new java.awt.Color(0, 0, 0));
        bt_crudPC1.setText("Crud pc");
        bt_crudPC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crudPC1ActionPerformed(evt);
            }
        });

        bt_salida.setBackground(new java.awt.Color(153, 153, 153));
        bt_salida.setForeground(new java.awt.Color(0, 0, 0));
        bt_salida.setText("Salir");
        bt_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_menuLayout = new javax.swing.GroupLayout(pn_menu);
        pn_menu.setLayout(pn_menuLayout);
        pn_menuLayout.setHorizontalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_crudPC, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_crudPC1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(233, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_tituloMenu)
                .addGap(253, 253, 253))
        );
        pn_menuLayout.setVerticalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lb_tituloMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(bt_crudPC1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(bt_crudPC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(bt_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salidaActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_salidaActionPerformed

    private void bt_ingreseLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ingreseLaptopActionPerformed
        tp_opcionesCrud.setSelectedIndex(1);       
    }//GEN-LAST:event_bt_ingreseLaptopActionPerformed

    private void atriHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atriHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atriHostActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Host = atriHost.getText();
        String Ip = atriIP.getText();
        String Mascara = atriMask.getText();
        String Ram = atriRam.getText();
        String Alm = atriAlm.getText();
        String tipo = (String) boxTipo.getSelectedItem();
        String grphcs = (String) boxGraphics.getSelectedItem();
        boolean t1;
        boolean t2;
        try {
            //check ip
            String[] checkIp = Ip.split("\\.");
          
            for (String string : checkIp) {
                if ((Integer.parseInt(string) < 0 || Integer.parseInt(string) > 255) || checkIp.length != 4) {
                    throw new Exception();
                }
            }
            if(checkIp.length  != 4){
                throw new Exception();
            }
            //check mask
            String[] maskOptions = {"192","224","240","248","252","254","255"};
            int x = 0;
            for (String maskOption : maskOptions) {
                if(maskOption.equals(Mascara)){
                    x++;
                }
            }
            if(x == 0){
                throw new Exception();
            }

            if (tipo.equals("HDD")) {
                t1 = true;
            } else {
                t1 = false;
            }

            if (grphcs.equals("Si")) {
                t2 = true;
            } else {
                t2 = false;
            }
            String mask = "255.255.255." + Mascara;
            PC_Escritorio nueva = new PC_Escritorio(Integer.parseInt(Ram), Integer.parseInt(Alm), t1, t2, Ip, mask, Host);
            pcs.add(nueva);
           atriHost.setText(null);
           atriAlm.setText(null);
           atriIP.setText(null);
           atriMask.setText(null);
           atriRam.setText(null);
           tp_opcionesCrud.setSelectedIndex(4);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void boxGraphicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxGraphicsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxGraphicsActionPerformed

    private void bt_ingreseEscritorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ingreseEscritorioActionPerformed
        tp_opcionesCrud.setSelectedIndex(3);
    }//GEN-LAST:event_bt_ingreseEscritorioActionPerformed

    private void bt_crudPC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crudPC1ActionPerformed
        wd_crudMenu.setVisible(true); 
        tp_opcionesCrud.setSelectedIndex(4);// TODO add your handling code here:
    }//GEN-LAST:event_bt_crudPC1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Host = tf_host.getText();
        String Ip = tf_ip.getText();
        String Mascara = tf_mask.getText();
        String Marca = tf_marca.getText(); 
        String def = tf_def.getText();
        boolean truth;
        
        try{
            //check ip
            String[] checkIp = Ip.split(".");
            for (String string : checkIp) {
                if ((Integer.parseInt(string) < 0 || Integer.parseInt(string) > 255) || checkIp.length != 4) {
                    throw new Exception();
                }
            }
            //check mask
            String[] maskOptions = {"192","224","240","248","252","254","255"};
            int x = 0;
            for (String maskOption : maskOptions) {
                if(maskOption.equals(Mascara)){
                    x++;
                }
            }
            if(x == 0){
                throw new Exception();
            }
            
            
             String mask = "255.255.255." + Mascara;
             pcs.add(new Laptop(Marca, def, rb_rgbSi.isSelected(), Ip, mask, Host));
             tf_host.setText(null);
             tf_ip.setText(null);
             tf_mask.setText(null);
             tf_marca.setText(null);
             tf_def.setText(null);
             tp_opcionesCrud.setSelectedIndex(4);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Hubo un error");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bt_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_listarActionPerformed
        String resp = "";
        int x = 1;
        for (PC pc : pcs) {
            resp += "PC " + x + "\n";
            resp += "Nombre: " + pc.getHostname() + " IP: " + pc.getIp() + " Mascara: " + pc.getMascara() + "\n\n";
            
        }
        
        ta_listar.setText(resp);
        tp_opcionesCrud.setSelectedIndex(2);        
       
    }//GEN-LAST:event_bt_listarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        DefaultComboBoxModel mod =(DefaultComboBoxModel) cb_eliminar.getModel();
        mod.removeAllElements();
        ArrayList<String> nombres = new ArrayList();
        
        for (PC pc : pcs) {
            nombres.add(pc.getHostname());
        }
        mod.addAll(nombres);
        tp_opcionesCrud.setSelectedIndex(0);
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void bt_elimnarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_elimnarActionPerformed
       String eliminar =  (String) cb_eliminar.getSelectedItem();
        for (PC pc : pcs) {
            if(pc.getHostname().equals(eliminar)){
                pcs.remove(pc);
                JOptionPane.showMessageDialog(null, "pc eliminada");
                break;
            }
        }
        tp_opcionesCrud.setSelectedIndex(4);
    }//GEN-LAST:event_bt_elimnarActionPerformed

    private void bt_regresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_regresoActionPerformed
        wd_crudMenu.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_regresoActionPerformed

    private void bt_crudPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crudPCActionPerformed
        this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_bt_crudPCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel at1;
    private javax.swing.JLabel at2;
    private javax.swing.JLabel at3;
    private javax.swing.JLabel at4;
    private javax.swing.JLabel at5;
    private javax.swing.JLabel at6;
    private javax.swing.JTextField atriAlm;
    private javax.swing.JTextField atriHost;
    private javax.swing.JTextField atriIP;
    private javax.swing.JTextField atriMask;
    private javax.swing.JTextField atriRam;
    private javax.swing.JPanel base;
    private javax.swing.ButtonGroup bg_grupo1;
    private javax.swing.JComboBox<String> boxGraphics;
    private javax.swing.JComboBox<String> boxTipo;
    private javax.swing.JButton bt_crudPC;
    private javax.swing.JButton bt_crudPC1;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_elimnar;
    private javax.swing.JButton bt_ingreseEscritorio;
    private javax.swing.JButton bt_ingreseLaptop;
    private javax.swing.JButton bt_listar;
    private javax.swing.JButton bt_regreso;
    private javax.swing.JButton bt_salida;
    private javax.swing.JComboBox<String> cb_eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_escritorioAtributo1;
    private javax.swing.JLabel lb_escritorioAtributo2;
    private javax.swing.JLabel lb_escritorioAtributo3;
    private javax.swing.JLabel lb_escritorioAtributo4;
    private javax.swing.JLabel lb_escritorioAtributo5;
    private javax.swing.JLabel lb_escritorioAtributo6;
    private javax.swing.JLabel lb_escritorioAtributo7;
    private javax.swing.JLabel lb_tituloMenu;
    private javax.swing.JPanel pn_Crear;
    private javax.swing.JPanel pn_Eliminar;
    private javax.swing.JPanel pn_crearLaptop;
    private javax.swing.JPanel pn_crudPrincipal;
    private javax.swing.JPanel pn_listar;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JRadioButton rb_rgbNo;
    private javax.swing.JRadioButton rb_rgbSi;
    private javax.swing.JTextArea ta_listar;
    private javax.swing.JTextField tf_def;
    private javax.swing.JTextField tf_host;
    private javax.swing.JTextField tf_ip;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_mask;
    private javax.swing.JTabbedPane tp_opcionesCrud;
    private javax.swing.JFrame wd_crudMenu;
    // End of variables declaration//GEN-END:variables
}
